[package]
name = "flowwatcher-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sysinfo = "0.35"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
