[package]
name = "flowwatcher-conditions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flowwatcher-triggers = { path = "../triggers" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
